import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#f2f6ff',
        'primary-fixed': '#ffdad5',
        'on-error': '#ffffff',
        background: '#fdf8f8',
        'primary-container': '#dc201e',
        'on-background': '#1c1b1b',
        error: '#ba1a1a',
        'surface-container-highest': '#e6e1e1',
        'on-surface-variant': '#5d3f3c',
        'error-container': '#ffdad6',
        'secondary-fixed': '#e7e2db',
        'outline-variant': '#e7bdb7',
        'on-secondary': '#ffffff',
        'tertiary-container': '#0074c0',
        'on-primary-fixed-variant': '#930007',
        'on-primary-container': '#fff3f2',
        outline: '#926f6a',
        'surface-container-low': '#f7f2f2',
        'on-surface': '#1c1b1b',
        'secondary-container': '#e7e2db',
        secondary: '#605e59',
        'clay-shadow': 'rgba(0,0,0,0.08)',
        'surface-container': '#f2edec',
        'grid-line': 'rgba(17,16,16,0.06)',
        'inverse-on-surface': '#f5f0ef',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#d1e4ff',
        'surface-container-high': '#ece7e6',
        'primary-fixed-dim': '#ffb4aa',
        primary: '#b4000c',
        surface: '#fdf8f8',
        'on-secondary-fixed-variant': '#494742',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#001d36',
        'on-tertiary-fixed-variant': '#00497c',
        'surface-variant': '#e6e1e1',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#410001',
        'inverse-surface': '#323030',
        'clay-highlight': '#FFFFFF',
        'on-secondary-container': '#67645f',
        tertiary: '#005b98',
        'surface-tint': '#c0000d',
        'surface-dim': '#ded9d8',
        'on-secondary-fixed': '#1d1c17',
        'on-error-container': '#93000a',
        'inverse-primary': '#ffb4aa',
        'surface-bright': '#fdf8f8',
        'tertiary-fixed-dim': '#9dcaff',
        'secondary-fixed-dim': '#cac6bf',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'safe-area': '32px',
        'margin-mobile': '20px',
        gutter: '24px',
        'margin-desktop': '48px',
        'grid-unit': '44px',
      },
      fontFamily: {
        'body-lg': ['Archivo Narrow'],
        'display-xl': ['Anton'],
        'headline-lg': ['Anton'],
        'body-md': ['Archivo Narrow'],
        'headline-lg-mobile': ['Anton'],
        'label-mono': ['JetBrains Mono'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'display-xl': ['120px', { lineHeight: '0.9', letterSpacing: '-0.04em', fontWeight: '400' }],
        'headline-lg': ['64px', { lineHeight: '0.9', letterSpacing: '-0.012em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg-mobile': ['40px', { lineHeight: '1.0', letterSpacing: '-0.012em', fontWeight: '400' }],
        'label-mono': ['11px', { lineHeight: '1.2', letterSpacing: '0.24em', fontWeight: '500' }],
      },
      boxShadow: {
        clay: '12px 12px 24px var(--tw-shadow-color, rgba(0,0,0,0.06)), -12px -12px 24px var(--tw-shadow-highlight, #ffffff)',
        'clay-sm': '6px 6px 12px var(--tw-shadow-color, rgba(0,0,0,0.06)), -6px -6px 12px var(--tw-shadow-highlight, #ffffff)',
        'clay-inset':
          'inset 12px 12px 24px var(--tw-shadow-color, rgba(0,0,0,0.06)), inset -12px -12px 24px var(--tw-shadow-highlight, #ffffff)',
        'clay-inset-sm':
          'inset 6px 6px 12px var(--tw-shadow-color, rgba(0,0,0,0.06)), inset -6px -6px 12px var(--tw-shadow-highlight, #ffffff)',
      },
    },
  },
  plugins: [forms, containerQueries],
}
